version: '2'

services:
    #nginx
    nginx-medzoner:
        image: "medzoner/nginx:latest"
        container_name: "nginx-${PROJECT_UID}"
        working_dir: "${PATHBASE}"
        restart: "always"
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - "${PATH_PROJECTS}:/var/www"
            # nginx vhost by env
            - "./etc/nginx/conf.d/default.${STAGING_ENV}.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
        networks:
            - "default"
        links:
            - ""
